name: Java Apps - Run Tests and package
on:
  push:
    branches: ["main"]
jobs:
    test_and_build:
      name: Test and build samples
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: setup JDK
          uses: actions/setup-java@v3
          with:
            java-version: '11'
            distribution: 'temurin'
        - name: run Tests
          run: mvn clean test | tee test.log
        - name: build artifacts
          run: mvn clean package -Dmaven.test.skip
        - name: setup artifacts
          run: mkdir artifacts && cp test.log target/*.jar artifacts
        - uses: actions/upload-artifact@v4
          with:
            name: Package
            path: artifacts
 